services:
  - type: web
    name: food-order-website
    runtime: node
    plan: free
    buildCommand: cd food-order-website && npm install && npm run build
    startCommand: cd food-order-website && npm install -g serve && serve -s dist -l 3000
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
